#!/usr/bin/env sh # for this to work you must configure sudo such that it will be able to run the command without password see this wiki page for information: - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
	mouse_follows_focus on \
	focus_follows_mouse autoraise \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_shadow off \
	split_ratio 0.50 \
	split_type auto \
	auto_balance on \
	top_padding 12 \
	bottom_padding 12 \
	left_padding 12 \
	right_padding 12 \
	window_gap 12 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

#yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Digital Color Meter$" sticky=on layer=above manage=off
#yabai -m window --toggle border

# JankyBorders
/opt/homebrew/bin/borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0

open -na /Applications/MonitorControl.app

echo "yabai configuration loaded.."
