alias ls='ls -lah --color=auto -F'
alias grep='grep --color'
alias ssh-kali='ssh default@192.168.64.7'
alias vim=/opt/homebrew/bin/nvim
export PATH=$PATH:/opt/homebrew/bin

eval "$(starship init zsh)"
